export const NEXT_WORD = 'NEXT_WORD'
export const START_TRIAL = 'START_TRIAL'
export const TICK = 'TICK'
export const END_TRIAL = 'END_TRIAL'
export const FINISHED = 'FINISHED'
export const USERNAME = 'USERNAME'
